name: CommandCodes
author: DziNeIT

version: 1.0
database: false
main: com.github.dzineit.commandcodes.CommandCodes

description: Allows the generation of one-time-use codes for running a command which the user may not be able to normally execute

commands:
    ccode:
        aliases: [cc, ccc]

permissions:
    commandcodes.generate:
        description: Allows command code generation
    commandcodes.remove:
        description: Allows command code removal
    commandcodes.view:
        description: Allows viewing current codes
    commandcodes.previous:
        description: Allows viewing previous codes
    commandcodes.redeem:
        description: Allows redeeming command codes
    commandcodes.admin:
        children:
            - commandcodes.generate:true
            - commandcodes.remove:true
    commandcodes.*:
        children:
            - commandcodes.generate:true
            - commandcodes.remove:true
            - commandcodes.admin:true
            - commandcodes.redeem:true
            - commandcodes.view:true
            - commandcodes.previous:true
